const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: `By accessing or using ZaraForge ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. We may update these terms at any time; continued use after changes constitutes acceptance.`,
  },
  {
    title: '2. Description of Service',
    body: `ZaraForge is an AI-powered creative platform offering a no-code app builder, music production studio, logo maker, background remover, and video editor. Features are provided on a subscription basis with a limited free tier.`,
  },
  {
    title: '3. Account Registration',
    body: `You must provide a valid email address to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must be at least 13 years of age to use the Service.`,
  },
  {
    title: '4. Free Tier',
    body: `The free tier includes limited AI generations, limited exports, and access to core features as described on the pricing page. ZaraForge reserves the right to modify free tier limits at any time with reasonable notice.`,
  },
  {
    title: '5. Subscriptions & Payment',
    body: `Pro subscriptions are billed monthly ($29/month) or annually ($199/year) via Stripe. Your subscription renews automatically at the end of each billing period. You may cancel at any time through your account settings; cancellation takes effect at the end of the current billing period. No partial refunds are issued for unused time. All prices are in USD.`,
  },
  {
    title: '6. Refund Policy',
    body: `We offer a 7-day satisfaction guarantee for first-time Pro subscribers. If you are unsatisfied within the first 7 days of your initial subscription, contact us at hello@zaraforge.app for a full refund. After 7 days, subscriptions are non-refundable.`,
  },
  {
    title: '7. Acceptable Use',
    body: `You agree not to use the Service to: (a) violate any applicable law or regulation; (b) infringe the intellectual property rights of others; (c) generate or distribute spam, malware, or harmful content; (d) attempt to reverse-engineer, scrape, or exploit the Service; (e) impersonate any person or entity. We reserve the right to suspend or terminate accounts that violate these terms without notice or refund.`,
  },
  {
    title: '8. Intellectual Property',
    body: `You retain full ownership of all content you create using ZaraForge. By using the Service, you grant ZaraForge a limited, non-exclusive license to process your content solely to provide the Service. ZaraForge retains all rights to its platform, technology, and brand.`,
  },
  {
    title: '9. AI-Generated Content',
    body: `Content generated by ZaraForge's AI tools is provided for your use. ZaraForge makes no warranty that AI output is accurate, original, or suitable for any particular purpose. You are solely responsible for reviewing and validating AI-generated content before use.`,
  },
  {
    title: '10. Disclaimer of Warranties',
    body: `The Service is provided "as is" and "as available" without warranties of any kind, express or implied, including but not limited to merchantability, fitness for a particular purpose, or non-infringement. ZaraForge does not guarantee uninterrupted or error-free operation.`,
  },
  {
    title: '11. Limitation of Liability',
    body: `To the maximum extent permitted by law, ZaraForge shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of data, revenue, or profits, arising out of or related to your use of the Service, even if advised of the possibility of such damages. Our total liability to you shall not exceed the amount you paid in the 12 months preceding the claim.`,
  },
  {
    title: '12. Termination',
    body: `Either party may terminate the agreement at any time. Upon termination, your right to access the Service ceases immediately. Sections covering intellectual property, disclaimers, and limitation of liability survive termination.`,
  },
  {
    title: '13. Governing Law',
    body: `These Terms are governed by the laws of the United States. Any disputes shall be resolved through binding arbitration or in the courts of competent jurisdiction, and you waive any right to a jury trial.`,
  },
  {
    title: '14. Contact',
    body: `For questions about these Terms, contact us at: hello@zaraforge.app`,
  },
]

const EFFECTIVE = 'May 25, 2026'

export default function TermsPage() {
  return (
    <div style={{
      minHeight: '100vh', background: '#09090b', color: '#e2e8f0',
      fontFamily: 'system-ui, -apple-system, sans-serif',
      WebkitFontSmoothing: 'antialiased',
    }}>
      {/* Nav */}
      <nav style={{
        position: 'sticky', top: 0, zIndex: 10,
        background: 'rgba(9,9,11,0.9)', backdropFilter: 'blur(20px)',
        borderBottom: '1px solid rgba(255,255,255,0.07)',
        padding: '0 32px', height: 60,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <a href="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>
          <img src="/zaraforge-logo.png" alt="ZaraForge" style={{ height: 28, width: 'auto' }} />
        </a>
        <a href="/" style={{ fontSize: 13, fontWeight: 600, color: 'rgba(255,255,255,0.4)', textDecoration: 'none' }}>← Back to home</a>
      </nav>

      {/* Content */}
      <div style={{ maxWidth: 760, margin: '0 auto', padding: '72px 32px 120px' }}>

        {/* Header */}
        <div style={{ marginBottom: 56 }}>
          <span style={{
            display: 'inline-block', fontSize: 11, fontWeight: 800, letterSpacing: '0.1em',
            textTransform: 'uppercase', color: '#34d399', marginBottom: 16,
            padding: '4px 12px', borderRadius: 99,
            background: 'rgba(52,211,153,0.08)', border: '1px solid rgba(52,211,153,0.18)',
          }}>Legal</span>
          <h1 style={{ fontSize: 'clamp(32px, 5vw, 52px)', fontWeight: 900, letterSpacing: '-0.028em', color: '#f1f5f9', lineHeight: 1.1, marginBottom: 16 }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: 14, color: 'rgba(255,255,255,0.3)', lineHeight: 1.6 }}>
            Effective date: {EFFECTIVE} &nbsp;·&nbsp; Last updated: {EFFECTIVE}
          </p>
        </div>

        {/* Intro */}
        <div style={{
          padding: '20px 24px', borderRadius: 14, marginBottom: 48,
          background: 'rgba(99,102,241,0.06)', border: '1px solid rgba(99,102,241,0.15)',
        }}>
          <p style={{ fontSize: 14, color: 'rgba(255,255,255,0.5)', lineHeight: 1.75, margin: 0 }}>
            Please read these Terms of Service carefully before using ZaraForge. These terms constitute a legally binding agreement between you and ZaraForge regarding your use of our platform and services.
          </p>
        </div>

        {/* Sections */}
        {SECTIONS.map((s, i) => (
          <div key={i} style={{ marginBottom: 40 }}>
            <h2 style={{ fontSize: 17, fontWeight: 800, color: '#f1f5f9', letterSpacing: '-0.01em', marginBottom: 12 }}>
              {s.title}
            </h2>
            <p style={{ fontSize: 14.5, color: 'rgba(255,255,255,0.45)', lineHeight: 1.85, margin: 0 }}>
              {s.body}
            </p>
            {i < SECTIONS.length - 1 && (
              <div style={{ height: 1, background: 'rgba(255,255,255,0.05)', marginTop: 40 }} />
            )}
          </div>
        ))}

        {/* Footer note */}
        <div style={{
          marginTop: 64, padding: '20px 24px', borderRadius: 14,
          background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12,
        }}>
          <span style={{ fontSize: 13, color: 'rgba(255,255,255,0.25)' }}>© 2026 ZaraForge. All rights reserved.</span>
          <a href="/privacy" style={{ fontSize: 13, color: '#34d399', textDecoration: 'none', fontWeight: 600 }}>Privacy Policy →</a>
        </div>
      </div>
    </div>
  )
}
